GbrSchedulero/GbrWebFrontend/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CHA.Data;
using GbrSchedulero;
using System.Dynamic;
using Microsoft.AspNetCore.Http;

namespace GbrWebFrontend.Controllers
{
    public class FlightsController : Controller
    {
        private readonly FlightScheduleDbContext _context;

        public FlightsController(FlightScheduleDbContext context)
        {
            _context = context;
        }

        // GET: Flights
        public async Task<IActionResult> Index()
        {
            //Huge query
            return View(await _context.Flights
                .Include(fl => fl.Plan)
                .Include(fl => fl.CrewAssignments)
                .ThenInclude(a => a.Qualification)
                .ThenInclude(q => q.Crewmember)
                .Include(fl => fl.Ship)
                .ThenInclude(sh => sh.AcType)
                .ToListAsync());
        }

        // GET: Flights/Create
        public IActionResult Create()
        {
            NewFlightViewModel model = new NewFlightViewModel();
            model.Flights = null;
            model.Airports = _context.Airports
                .Where(a => true)
                .AsEnumerable();
            model.Aircrafts = _context.Aircrafts
                .Where(a => true)
                .Include(a => a.AcType)
                .AsEnumerable();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateFlight(string flightNumber, int aircraftId, int originSelection, int destinationSelection,
            DateTime departDate, DateTime arriveDate)
        {
            FlightPlan plan = new FlightPlan(flightNumber, originSelection, destinationSelection, departDate, arriveDate);
            _context.Add(plan);

            Aircraft ac = _context.Aircrafts.Where(ac => ac.AircraftID == aircraftId).FirstOrDefault();

            Flight flight = new Flight(plan, ac, 0);

            _context.Add(flight);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult EditFlight(IFormCollection formCollection)
        {
            IEnumerable<int> ids = null;
            if (!string.IsNullOrEmpty(formCollection["qualificationID"]))
            {
                string qualificationIDs = formCollection["qualificationID"];
                ids = qualificationIDs.Split(",").Select(a => int.Parse(a));
                
                //No selection
                if (ids == null || ids.Count() == 0)
                    return RedirectToAction(nameof(Index));
            }

            int flightId = int.Parse(formCollection["flightId"]);
            Flight flight = _context.Flights.Where(fl => fl.FlightID == flightId).FirstOrDefault();

            //Add crewmembers to flight
            IEnumerable<CrewQualification> quals = _context.Qualifications.Where(q => ids.Contains(q.CrewQualificationID));

            foreach (CrewQualification qual in quals)
            {
                FlightCrewAssignment assignment = new FlightCrewAssignment(flight, qual);
                _context.Add(assignment);
            }

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: Flights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }

            AircraftType type = _context.Flights
                .Where(fl => fl.FlightID == id)
                .Include(fl => fl.Ship)
                .ThenInclude(s => s.AcType)
                .FirstOrDefault().Ship.AcType;

            //IEnumerable<FlightCrewAssignment> currentCrew = (from q in _context.Qualifications
            //                  join a in _context.Assignments on q.CrewQualificationID equals a.CrewQualificationID
            //                  join c in _context.Crewmembers on q.CrewmemberID equals c.CrewmemberID
            //                  where a.FlightID == (int)id
            //                  select a);

            IEnumerable<FlightCrewAssignment> currentCrew = _context.Assignments
                .Where(a => a.FlightID == (int)id)
                .Include(a => a.Qualification)
                .ThenInclude(q => q.Crewmember)
                .AsEnumerable();
                
            //What
            IEnumerable<CrewQualification> model = (from c in _context.Crewmembers
                              join q in _context.Qualifications on c.CrewmemberID equals q.CrewmemberID
                              join t in _context.AircraftTypes on q.AircraftTypeID equals t.AircraftTypeID
                              where t.AircraftTypeID == type.AircraftTypeID
                              orderby q.Station
                              select new CrewQualification {
                                      CrewQualificationID = q.CrewQualificationID,
                                      Station = q.Station,
                                      Crewmember = c
                              });

            return View(new CrewAssignmentViewModel {FlightID = (int)id, AvailableCrew = model, CurrentCrew = currentCrew });
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FlightID,Passengers")] Flight flight)
        {
            if (id != flight.FlightID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.FlightID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .FirstOrDefaultAsync(m => m.FlightID == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flight = await _context.Flights.FindAsync(id);
            _context.Flights.Remove(flight);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightExists(int id)
        {
            return _context.Flights.Any(e => e.FlightID == id);
        }
    }
}

GbrSchedulero/GbrWebFrontend/Views/Flights/Create.cshtml
@using GbrSchedulero
@model NewFlightViewModel

@{
    ViewData["Title"] = "Create Flight";
}
<div>
    <h1>Create Flight</h1>
    <hr />
    @using (Html.BeginForm("CreateFlight", "Flights", FormMethod.Post))
    {
        <div class="row">
            <div class="col-md">
                <p class="flcontrollab">Flight Number</p>
                @Html.TextBox("flightNumber")
            </div>
            <div class="col-md">
                <p class="flcontrollab">Departure Time</p>
                <input class="datetime" id="departDate" name="departDate" type="datetime-local" value="">
            </div>
            <div class="col-md">
                <p class="flcontrollab">Arrival Time</p>
                <input class="datetime" id="arriveDate" name="arriveDate" type="datetime-local" value="">
            </div>
        </div>
        <div class="row">
            <table style="table-layout: fixed; width: 100%;">
                <colgroup>
                    <col span="1" style="width: 32px" />
                </colgroup>
                <thead>
                    <tr>
                        <th />
                        <th>Aircraft</th>
                        <th>Type</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Aircraft ac in Model.Aircrafts)
                    {
                        <tr>
                            <td align="center" valign="middle">
                                @Html.RadioButton("aircraftId", ac.AircraftID)
                            </td>
                            <td>
                                @ac.Registration
                            </td>
                            <td>
                                @ac.AcType
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-md" style="padding-left: 0; padding-top: 6pt; padding-right: 0;">
                <table style="table-layout: fixed; width: 100%;">
                    <colgroup>
                        <col span="1" style="width: 32px" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th />
                            <th>
                                Origin
                            </th>
                        </tr>
                    </thead>
                    @foreach (Airport plan in Model.Airports)
                    {
                        <tr>
                            <td align="center" valign="middle">
                                @Html.RadioButton("originSelection", plan.AirportId)
                            </td>
                            <td>
                                @plan.AirportName
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div class="col-md" style="padding-right: 0; padding-left: 6pt; padding-top: 6pt;">
                <table style="table-layout: fixed; width: 100%;">
                    <colgroup>
                        <col span="1" style="width: 32px" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th />
                            <th>
                                Destination
                            </th>
                        </tr>
                    </thead>
                    @foreach (Airport plan in Model.Airports)
                    {
                        <tr>
                            <td align="center" valign="middle">
                                @Html.RadioButton("destinationSelection", plan.AirportId)
                            </td>
                            <td>
                                @plan.AirportName
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
        <div class="row" style="padding-top: 6pt;">
            <div class="col-sm">
                <input type="submit" value="Submit" style="border-radius: 20px; padding-top: 5pt; padding-bottom: 5pt; padding-left: 20pt; padding-right: 20pt" />
            </div>
            <div class="col-sm">
                <a asp-action="Index">
                    <button type="button" class="btn btn-danger" style="border-radius: 20px; padding-top: 5pt; padding-bottom: 5pt; padding-left: 20pt; padding-right: 20pt">Return to Flights</button>
                </a>
            </div>
        </div>
    }
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GbrSchedulero/GbrWebFrontend/Views/Flights/Delete.cshtml
@model GbrSchedulero.Flight

@{
    ViewData["Title"] = "Delete";
}

<h1>Cancel</h1>

<h3>Are you sure you want to cancel this flight?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Passengers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Passengers)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FlightID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GbrSchedulero/GbrWebFrontend/Views/Flights/Edit.cshtml
@using GbrSchedulero
@model CrewAssignmentViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Crewmembers</h1>
<hr />
<div class="row">
    @using (Html.BeginForm("EditFlight", "Flights", FormMethod.Post))
    {
        <input type="hidden" name="flightId" value="@Model.FlightID" />
        <br/>
        <h2>Current Crew</h2>
        <hr />
        <div class="row">
            <table style="table-layout: fixed; width: 100%;">
                <colgroup>
                    <col span="1" style="width: 32px" />
                </colgroup>
                <thead>
                    <tr>
                        <th />
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Position</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (FlightCrewAssignment line in Model.CurrentCrew)
                    {
                        <tr>
                            <td align="center" valign="middle">
                                R
                            </td>
                            <td>
                                @line.Qualification.Crewmember.FirstName
                            </td>
                            <td>
                                @line.Qualification.Crewmember.LastName
                            </td>
                            <td>
                                @line.Qualification.Station.ToString()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <br />
        <h2>Available Crew</h2>
        <hr />
        <div class="row">
            <table style="table-layout: fixed; width: 100%;">
                <colgroup>
                    <col span="1" style="width: 32px" />
                </colgroup>
                <thead>
                    <tr>
                        <th />
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Position</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (CrewQualification line in Model.AvailableCrew)
                    {
                        <tr>
                            <td align="center" valign="middle">
                                <input type="checkbox" name="qualificationID" value="@line.CrewQualificationID" />
                            </td>
                            <td>
                                @line.Crewmember.FirstName
                            </td>
                            <td>
                                @line.Crewmember.LastName
                            </td>
                            <td>
                                @line.Station.ToString()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="row" style="padding-top: 6pt;">
            <div class="col-sm">
                <input type="submit" value="Submit" style="border-radius: 20px; padding-top: 5pt; padding-bottom: 5pt; padding-left: 20pt; padding-right: 20pt" />
            </div>
            <div class="col-sm">
                <a asp-action="Index">
                    <button type="button" class="btn btn-danger" style="border-radius: 20px; padding-top: 5pt; padding-bottom: 5pt; padding-left: 20pt; padding-right: 20pt">Return to Flights</button>
                </a>
            </div>
        </div>
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GbrSchedulero/GbrWebFrontend/Views/Flights/Index.cshtml
@model IEnumerable<GbrSchedulero.Flight>

@{
    ViewData["Title"] = "Index";
}
<header>
</header>
<h1>Flights Index</h1>
<hr />
<p>
    <a asp-action="Create">Create Flight</a>
</p>
<table class="table">
    <thead>

    </thead>
    <tbody>
        <tr>
            <th>
                Flight Number
            </th>
            <th>
                Depart
            </th>
            <th>
                Arrive
            </th>
            <th>
                Aircraft
            </th>
            <th>
                Passengers
            </th>
            <th>
                Status
            </th>
            <th>
                Actions
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Plan.FlightNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Plan.DepartureTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Plan.ArrivalTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ship.Registration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Passengers)
                </td>
                <td>
                    @{
                        bool crewValid = item.ValidCrew();
                        @(crewValid?"Ready":"Needs Crew")
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.FlightID">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.FlightID">Cancel</a>
                </td>
            </tr>
        }
    </tbody>
</table>